name: auto_size_styled_text
description: Text widget with formatted text using tags. Makes it easier to use formatted text in multilingual applications.Automatically resizes text to fit perfectly within its bounds. 
version: 1.1.0
homepage: https://github.com/barisozbey/auto_size_styled_text
repository: https://github.com/barisozbey/auto_size_styled_text
issue_tracker: https://github.com/barisozbey/auto_size_styled_text/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  xmlstream: ^1.0.0
  auto_size_text_pk: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter